version: "3"

services:
  apache:
    build:
      context: httpd
    ports:
      - 4545:80
    volumes:
      - ./src:/var/www/html
      - ./log:/var/log/apache2
    depends_on:
      - bd

  nginx:
    image: nginx:1.13
    ports:
      - 4542:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache

  bd:
    image: mysql:5.7
    volumes:
      - ./bd/data:/var/lib/mysql
      - ./bd:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
